name: google_maps_place_picker_mb
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 4.0.0
homepage: https://github.com/martin-braun-net/google_maps_place_picker_mb

environment:
  sdk: ^3.8.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  google_api_headers: ^4.5.7
  google_maps_flutter: ^2.12.3
  flutter_google_maps_webservices: ^1.1.1
  http: ^1.4.0
  provider: ^6.1.5
  tuple: ^2.0.2
  uuid: ^4.5.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

false_secrets:
  - /example/lib/keys.dart
  - /example/android/app/src/main/AndroidManifest.xml
  - /example/ios/Runner/AppDelegate.swift
